name: Flask CI Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . -t my-flask-app

    - name: Run Tests
      run: docker run my-flask-app python -m unittest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Image to Docker Hub
      run: |
        docker tag my-flask-app ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:latest
